export enum MessageType {
  /* ======================
     CATEGORY
  ====================== */
  CREATE_CATEGORY = "CREATE_CATEGORY",
  UPDATE_CATEGORY = "UPDATE_CATEGORY",
  GET_CATEGORIES = "GET_CATEGORIES",
  DELETE_CATEGORIES = "DELETE_CATEGORIES",
  GET_CATEGORIES_BY_IDS = "GET_CATEGORIES_BY_IDS",
  GET_CATEGORIES_BY_NAME = "GET_CATEGORIES_BY_NAME",
  UPDATE_CATEGORY_BY_NAME = "UPDATE_CATEGORY_BY_NAME",
  DELETE_CATEGORIES_BY_NAME = "DELETE_CATEGORIES_BY_NAME",

  /* ======================
     TASK
  ====================== */
  CREATE_TASK = "CREATE_TASK",
  GET_TASKS_BY_CATEGORY_ID = "GET_TASKS_BY_CATEGORY_ID",
  GET_TASK_BY_ID = "GET_TASK_BY_ID",
  UPDATE_TASK = "UPDATE_TASK",
  MOVE_TASK = "MOVE_TASK",
  DELETE_TASKS_FROM_CATEGORY = "DELETE_TASKS_FROM_CATEGORY",

  CREATE_TASK_BY_CATEGORY_NAME = "CREATE_TASK_BY_CATEGORY_NAME",
  MOVE_TASK_BY_NAME = "MOVE_TASK_BY_NAME",
  DELETE_TASKS_BY_NAME = "DELETE_TASKS_BY_NAME",
  GET_TASKS_BY_CATEGORY_NAME = "GET_TASKS_BY_CATEGORY_NAME",
  GET_TASK_BY_NAME = "GET_TASK_BY_NAME",
  UPDATE_TASK_BY_NAME = "UPDATE_TASK_BY_NAME",

  /* ======================
     NOTE
  ====================== */
  CREATE_NOTE = "CREATE_NOTE",
  GET_NOTES_BY_CATEGORY_ID = "GET_NOTES_BY_CATEGORY_ID",
  GET_NOTE_BY_ID = "GET_NOTE_BY_ID",
  UPDATE_NOTE = "UPDATE_NOTE",
  MOVE_NOTE = "MOVE_NOTE",
  DELETE_NOTES = "DELETE_NOTES",

  /* ======================
     USER
  ====================== */
  GET_CURRENT_USER = "GET_CURRENT_USER",
}
